config/routes.rb
Rails.application.routes.draw do
  get 'subcategory/show'
  get 'subcategory/index'
  

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }


 # resources :categories, only: [:show]
  #resources :products

  resources :categories do
    resources :subcategories, only: [:show], controller: 'subcategory'
  end
    
  resources :products
  



  resources :shopping_cart_items, only: [:create, :update, :destroy]
  resource :shopping_cart, only: [:show]
  

  resources :orders, only: [:new, :create, :show]


  post 'shopping_cart_items/:id/remove', to: 'shopping_cart_items#remove', as: 'remove_shopping_cart_item'


  get "up" => "rails/health#show", as: :rails_health_check

  
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :subcategories, dependent: :destroy
    has_many :products, through: :subcategories
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy 
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :subcategory
  has_one :category, through: :subcategory
  has_one_attached :image
  
  
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord

    belongs_to :user
    has_many :shopping_cart_items
    
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ApplicationRecord
  belongs_to :shopping_cart
  belongs_to :product
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  belongs_to :category
  has_many :products, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_one :shopping_cart, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_cart_items_count

  private

  def set_cart_items_count
    @cart_items_count = current_user.shopping_cart.shopping_cart_items.count if user_signed_in?
  end
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/:id
  def show
    @subcategories = @category.subcategories
    @products = @category.products
  end

  private

  # Set the category based on params[:id]
  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_order, only: [:show]
  
    def new
      @shopping_cart = current_user.shopping_cart
      if @shopping_cart.shopping_cart_items.empty?
        redirect_to shopping_cart_path, alert: 'Your cart is empty!'
      else
        @order = current_user.orders.build
        @order_items = @shopping_cart.shopping_cart_items
      end
    end
  
    def create
      @shopping_cart = current_user.shopping_cart
      @order = current_user.orders.build(order_params)
  
      @shopping_cart.shopping_cart_items.each do |item|
        @order.order_items.build(product: item.product, quantity: item.quantity)
      end
  
      if @order.save
        @shopping_cart.shopping_cart_items.destroy_all
        redirect_to order_path(@order), notice: 'Order successfully placed.'
      else
        render :new
      end
    end
  
    # Adding the show action
    def show
      # @order is already set by the before_action :set_order
      @order_items = @order.order_items
    end
  
    private
  
    # DRY method to find the order for actions like show
    def set_order
      @order = current_user.orders.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, alert: 'Order not found.'
    end
  
    # Strong parameters for order
    def order_params
      params.require(:order).permit(:status)  # Add any other parameters you need
    end
  end
  

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit, :create, :update]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @subcategories = @product.category.nil? ? [] : @product.category.subcategories
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Set categories for dropdown in form
    def set_categories
      @categories = Category.all
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :description,:image, :subcategory_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shopping_cart_helper.rb
module ShoppingCartHelper
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/helpers/subcategory_helper.rb
module SubcategoryHelper
end

app/views/categories/show.html.erb
<h1 class="text-3xl font-bold text-gray-900"><%= @category.name %></h1>

<!-- Liste des produits -->
<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 mt-6">
  <% if @products.any? %>
    <% @products.each do |product| %>
      <div class="group border rounded-lg shadow-md overflow-hidden">
        <%= link_to product_path(product) do %>
          <%= image_tag product.image.variant(resize_to_limit: [300, 300]), alt: product.name, class: 'w-full h-48 object-cover' if product.image.attached? %>
          <div class="p-4">
            <h3 class="text-lg font-semibold text-gray-900"><%= product.name %></h3>
            <p class="mt-2 text-gray-600">$<%= product.price %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <p class="text-gray-600">Aucun produit disponible pour cette catégorie.</p>
  <% end %>
</div>

app/views/orders/new.html.erb
<section class="bg-white py-8 antialiased  md:py-16">
  <div class="mx-auto max-w-screen-xl px-4 2xl:px-0">
    <div class="mx-auto max-w-3xl">
      <h2 class="text-xl font-semibold text-gray-900 sm:text-2xl">Order Summary</h2>

      <div class="mt-6 space-y-4 border-b border-t border-gray-200 py-8 sm:mt-8">
        <h4 class="text-lg font-semibold text-gray-900">Billing & Delivery Information</h4>

        <dl>
          <dt class="text-base font-medium text-gray-900">Individual</dt>
          <dd class="mt-1 text-base font-normal text-gray-500 dark:text-gray-400">
            <%= current_user.email%>
          </dd>
          <dd class="mt-5">  <%= link_to 'Edit', edit_user_registration_path, class: 'text-base text-white font-medium py-2 px-5 bg-gray-800 rounded' %></dd>
        </dl>
      </div>

      <div class="mt-6 sm:mt-8">
        <% if @shopping_cart.shopping_cart_items.any? %>

          <div class="relative overflow-x-auto border-b border-gray-200">
            <table class="w-full text-left font-medium text-gray-900 md:table-fixed">
              <tbody class="divide-y divide-gray-200 dark:divide-gray-800">
                <% @order_items.each do |item| %>
                  <tr>
                    <td class="whitespace-nowrap py-4 md:w-[384px]">
                      <div class="flex items-center gap-4">
                        <% if item.product && item.product.image.attached? %>
                          <%= image_tag item.product.image, class: "h-20 w-20 object-cover" %>
                        <% else %>
                          <%= image_tag "default_img_product.png", class: "h-20 w-20 object-cover" %>
                        <% end %>
                        <%= link_to item.product.name, product_path(item.product), class: "text-lg font-medium text-gray-900 hover:underline dark:text-white" %>
                      </div>
                    </td>
                    <td class="p-4 text-base font-normal text-gray-900">x<%= item.quantity %></td>
                    <td class="p-4 text-right text-base font-bold text-gray-900">
                      <%= number_to_currency(item.product.price * item.quantity) %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <div class="mt-4 space-y-6">
            <h4 class="text-xl font-semibold text-gray-900">Order Summary</h4>

            <div class="space-y-4">
              <div class="space-y-2">
                <dl class="flex items-center justify-between gap-4 border-t border-gray-200 pt-2">
                  <dt class="text-lg font-bold text-gray-900">Total</dt>
                  <dd class="text-lg font-bold text-gray-900">
                    <%= number_to_currency(@shopping_cart.shopping_cart_items.sum { |item| item.product.price * item.quantity }) %>
                  </dd>
                </dl>
              </div>
            </div>

            <div class="gap-4 sm:flex sm:items-center">
              

              <%= form_with model: @order, url: orders_path, local: true do |f| %>
                <%= f.hidden_field :status, value: "Pending" %>
                <%= f.submit 'Place Order', class: "mt-4 flex items-center justify-center rounded-lg bg-green-700 px-5 py-2.5 text-sm font-medium text-white  " %>
              <% end %>
            </div>
          </div>
        <% else %>
          <p>Your cart is empty.</p>
           <%= link_to 'Return to shopping', products_path, class: "py-2.5 px-5 text-sm font-medium text-gray-900  bg-white rounded-lg border border-gray-200" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/orders/show.html.erb
<section class="bg-white py-8 antialiased dark:bg-gray-900 md:py-16">
  <div class="mx-auto max-w-2xl px-4 2xl:px-0">
    <h2 class="text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl mb-2">
      Thanks for your order!
    </h2>
    <p class="text-gray-500 dark:text-gray-400 mb-6 md:mb-8">
      Your order <span class="font-bold">N°<%= @order.id %></span> will be processed within 24 hours during working days. We will notify you by email once your order has been shipped.
    </p>

  
      <div class="space-y-4 sm:space-y-2 rounded-lg border border-gray-100 bg-gray-50 p-6 dark:border-gray-700 dark:bg-gray-800 mb-6 md:mb-8">
        <dl class="sm:flex items-center justify-between gap-4">
          <dt class="font-normal mb-1 sm:mb-0 text-gray-500 dark:text-gray-400">Date</dt>
          <dd class="font-medium text-gray-900 dark:text-white sm:text-end"><%= @order.created_at %></dd>
        </dl>
        <dl class="sm:flex items-center justify-between gap-4">
          <dt class="font-normal mb-1 sm:mb-0 text-gray-500 dark:text-gray-400">Payment Method</dt>
          <dd class="font-medium text-gray-900 dark:text-white sm:text-end">JPMorgan monthly installments</dd>
        </dl>
        <dl class="sm:flex items-center justify-between gap-4">
          <dt class="font-normal mb-1 sm:mb-0 text-gray-500 dark:text-gray-400">Name</dt>
          <dd class="font-medium text-gray-900 dark:text-white sm:text-end"><%= current_user.email %></dd>
        </dl>
        <dl class="sm:flex items-center justify-between gap-4">
          <dt class="font-normal mb-1 sm:mb-0 text-gray-500 dark:text-gray-400">Address</dt>
          <dd class="font-medium text-gray-900 dark:text-white sm:text-end">34 Scott Street, San Francisco, California, USA</dd>
        </dl>
        <dl class="sm:flex items-center justify-between gap-4">
          <dt class="font-normal mb-1 sm:mb-0 text-gray-500 dark:text-gray-400">Phone</dt>
          <dd class="font-medium text-gray-900 dark:text-white sm:text-end">+(123) 456 7890</dd>
        </dl>
        <dl class="sm:flex items-center justify-between gap-4">
          <dt class="font-normal mb-1 sm:mb-0 text-gray-500 dark:text-gray-400">Total</dt>
          
          <dd class="font-medium text-gray-900 dark:text-white sm:text-end">
            <%= number_to_currency(@order.order_items.sum { |item| item.product.price * item.quantity }) %>
          </dd>
           

        </dl>
      </div>

    <div class="flex items-center space-x-4">
     
 
       <%= link_to 'Return to shopping', products_path, class: "py-2.5 px-5 text-sm font-medium text-gray-900  bg-white rounded-lg border border-gray-200" %>

    </div>
  </div>
</section>

app/views/products/_affiche.html.erb
<div class="container mx-auto bg-white py-8 px-4">

  <div class="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 ">

   <% @products.each do |product| %>


    <div class="group flex flex-col border border-gray-200 bg-white shadow-lg rounded-lg overflow-hidden hover:shadow-xl transition duration-300 ease-in-out">
      
      <a class="relative flex h-64 overflow-hidden" href="#">
        <%= image_tag product.image, class: 'w-full h-full object-cover transition-transform duration-300 group-hover:scale-110' if product.image.attached? %>
        <div class="absolute -right-12 bottom-4 space-y-2 transition-all duration-300 group-hover:right-4">
          <button class="flex h-10 w-10 items-center justify-center bg-gray-900 text-white rounded-full hover:bg-gray-700 transition">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
              <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd" />
            </svg>
          </button>
        </div>
      </a>
      
      <div class="p-5">
        <a href="#">
          <h5 class="text-lg font-semibold text-gray-900 truncate"><%= link_to product.name, product_path(product) %></h5>
        </a>
        <div class="mt-3 flex items-center justify-between">
          <p>
            <span class="text-xl font-bold text-gray-900"><%= number_to_currency(product.price) %></span>
            <p class="flex" >
             <span class="text-sm font-bold text-red-800"><%= product.subcategory.category.name %></span> - 
            <span class="text-sm font-bold text-gray-900"><%= product.subcategory.name %></span>

            </p>
     
          </p>
        </div>
     

           <%= form_with url: shopping_cart_items_path, method: :post do |form| %>
            <%= form.hidden_field :product_id, value: product.id %>
            <%= form.label  :quantity ,class:"text-sm font-bold text-gray-900 mx-2" %>
            <%= form.number_field :quantity, value: 1, min: 1, class: "w-16 p-2 text-center bg-gray-100 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500" %>
              <%= form.submit 'Add to Cart', class: "mt-4 flex items-center justify-center bg-gray-900 text-white px-4 py-2 rounded hover:bg-gray-700 transition" %>
          <% end %>
      </div>
    </div>

    <% end %>
    
  </div>
</div>

app/views/products/_form.html.erb
<section class="bg-white mb-8">
  <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
    <h2 class="mb-4 text-xl font-bold text-gray-900"><%= action_name.capitalize %> Product</h2>
    
    <%= form_with(model: @product, local: true, html: { multipart: true }) do |form| %>


      <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



      <div class="grid gap-4 sm:grid-cols-2 sm:gap-6"> 
        <!-- Name -->
        <div class="sm:col-span-2">
          <%= form.label :name, class: "block mb-2 text-sm font-medium text-gray-900" %> 
          <%= form.text_field :name, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
          <% @product.errors.full_messages_for(:name).each do |message| %>
            <div class="text-red-600"><%= message %></div>
          <% end %>
        </div>
        
        <!-- Price -->
        <div class="w-full">
          <%= form.label :price, class: "block mb-2 text-sm font-medium text-gray-900" %> 
          <%= form.number_field :price, step: 0.01, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
          <% @product.errors.full_messages_for(:price).each do |message| %>
            <div class="text-red-600"><%= message %></div>
          <% end %>
        </div>
        
        <!-- Image -->
        <div class="w-full">
          <%= form.label :image, class: "block mb-2 text-sm font-medium text-gray-900" %> 
          <%= form.file_field :image, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
        </div>
        
        <!-- Category -->
        <div>
          <%= form.label :category_id, 'Category', class: "block mb-2 text-sm font-medium text-gray-900" %>
          <%= form.collection_select :category_id, @categories, :id, :name, prompt: 'Select a category', onchange: 'this.form.submit();', class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5" %>
        </div>
        
        <!-- Subcategory -->
        <div>
          <%= form.label :subcategory_id, 'Subcategory', class: "block mb-2 text-sm font-medium text-gray-900" %>
          <%= form.collection_select :subcategory_id, @categories.flat_map(&:subcategories), :id, :name, prompt: 'Select a subcategory', class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5" %>
        </div>
        
        <!-- Description -->
        <div class="sm:col-span-2">
          <%= form.label :description, class: "block mb-2 text-sm font-medium text-gray-900" %><br>
          <%= form.text_area :description, class: "block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300", placeholder: "Your description here" %>
       
        </div>
        
     
        
      </div>
      
      <!-- Submit button -->
      <div class="mt-4 bg-black text-white font-medium rounded-lg text-sm px-5 py-2.5 text-center">
        <%= form.submit %>
      </div>
    
    <% end %>
  </div>
</section>

app/views/products/edit.html.erb
<%= render "form" ,product: @product %>

app/views/products/index.html.erb
<%= render "affiche" ,product: @products %>

app/views/products/new.html.erb
<%= render "form" ,product: @product %>

app/views/products/show.html.erb
<section class="py-8 bg-white md:py-16 dark:bg-gray-900 antialiased">
  <div class="max-w-screen-xl px-4 mx-auto 2xl:px-0">
    <div class="lg:grid lg:grid-cols-2 lg:gap-8 xl:gap-16">
      
      <!-- Image Section -->
      <div class="shrink-0 max-w-md lg:max-w-lg mx-auto">
        <div class="overflow-hidden rounded-lg shadow-lg">
          <%= image_tag @product.image, class: "w-full h-auto object-cover" if @product.image.attached? %>
        </div>
      </div>

      <!-- Product Details Section -->
      <div class="mt-6 sm:mt-8 lg:mt-0">
        <!-- Product Name -->
        <h1 class="text-xl font-semibold text-gray-900 sm:text-2xl dark:text-white">
          <%= @product.name %>
        </h1>

        <!-- Product Price -->
        <div class="mt-4 flex items-center">
          <p class="text-2xl font-extrabold text-gray-900 sm:text-3xl dark:text-white">
            $<%= @product.price %>
          </p>
        </div>

        <!-- Add to Favorites & Cart -->
        <div class="mt-6 flex gap-4 sm:items-center">
          
          <!-- Add to Favorites Button -->
          <a href="#" title="Add to favorites"
            class="flex items-center justify-center py-2.5 px-5 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-primary-700 focus:outline-none focus:ring-4 focus:ring-gray-100 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-gray-700"
            role="button">
            <svg class="w-5 h-5 mr-2" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M12.01 6.001C6.5 1 1 8 5.782 13.001L12.011 20l6.23-7C23 8 17.5 1 12.01 6.002Z" />
            </svg>
            Add to favorites
          </a>

          <!-- Add to Cart Form -->
          <%= form_with url: shopping_cart_items_path, method: :post, class: "flex items-center space-x-3" do |form| %>
            <%= form.hidden_field :product_id, value: @product.id %>
            <%= form.number_field :quantity, value: 1, min: 1, class: "w-16 p-2 text-center bg-gray-100 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500" %>
            <%= form.submit 'Add to Cart', class: "py-2.5 px-5 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 focus:outline-none focus:ring-4 focus:ring-blue-200 dark:focus:ring-blue-900" %>

          <% end %>
        </div>

        <!-- Separator -->
        <hr class="my-6 border-gray-200 dark:border-gray-800" />

        <!-- Product Description -->
        <p class="mb-6 text-gray-500 dark:text-gray-400">
          <%= @product.description %>
        </p>

        <!-- Actions (Remove and Edit) -->
        <div class="flex space-x-4">
          <%= button_to 'Remove', product_path(@product), method: 'delete', class: "py-2.5 px-5 text-sm font-medium text-white bg-red-600 rounded-lg hover:bg-red-700 focus:outline-none focus:ring-4 focus:ring-red-200 dark:focus:ring-red-900", data: { confirm: 'Are you sure?' } %>
          <%= link_to 'Edit', edit_product_path(@product), class: "py-2.5 px-5 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-primary-700 focus:outline-none focus:ring-4 focus:ring-gray-100 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-gray-700" %>
        </div>
      </div>

    </div>
  </div>
</section>